# Atividade Avaliativa — Estrutura de Dados II

### Engenharia de Software

**Professora:** Karla Roberta  
**Estudantes:** Pietro Vianna da Rocha e João Pedro Alves de Sousa  
**Linguagem:** Python 3.12  

---

Este notebook reúne os códigos desenvolvidos para a atividade. A ideia foi separar cada parte de forma clara, explicando o que está sendo feito, por que o código foi usado e o que os resultados mostram.

> Para reproduzir os resultados, basta executar as células na ordem em que aparecem.

## Sumário

1. Bubble Sort  
2. Quick Sort  
3. Comparação experimental  
4. Busca sequencial em matriz  
5. Experimento com matrizes de tamanhos diferentes  
6. Hands On 1 — Array de temperaturas  
7. Hands On 2 — Matriz de sensores  
8. Conclusão

---
# 1. Bubble Sort

## O que este código faz
O **Bubble Sort** é um algoritmo de ordenação que compara elementos adjacentes e realiza trocas quando eles estão fora de ordem.

## Objetivo desta parte
Implementar o Bubble Sort com:
- contagem de comparações;
- contagem de trocas;
- parada antecipada quando o vetor já estiver ordenado.

## Complexidade
- Melhor caso: **O(n)**
- Caso médio: **O(n²)**
- Pior caso: **O(n²)**

In [1]:
def bubble_sort(arr):
    """Ordena uma cópia de arr usando Bubble Sort.

    Retorna:
        lista_ordenada, comparacoes, trocas
    """
    a = arr[:]
    n = len(a)

    comparacoes = 0
    trocas = 0

    for i in range(n - 1):
        trocou = False

        for j in range(n - 1 - i):
            comparacoes += 1

            if a[j] > a[j + 1]:
                a[j], a[j + 1] = a[j + 1], a[j]
                trocas += 1
                trocou = True

        if not trocou:
            break

    return a, comparacoes, trocas

### Testando o Bubble Sort
A célula abaixo usa um vetor pequeno para conferir se a ordenação está funcionando como esperado.

In [2]:
vetor_teste = [5, 1, 4, 2, 8]

ordenado, comparacoes, trocas = bubble_sort(vetor_teste)

print("Vetor original :", vetor_teste)
print("Vetor ordenado :", ordenado)
print("Comparações    :", comparacoes)
print("Trocas         :", trocas)

Vetor original : [5, 1, 4, 2, 8]
Vetor ordenado : [1, 2, 4, 5, 8]
Comparações    : 9
Trocas         : 4

---
# 2. Quick Sort

## O que este código faz
O **Quick Sort** utiliza a estratégia de **dividir para conquistar**.

O algoritmo escolhe um pivô, reorganiza os elementos em torno dele e repete o processo recursivamente.

## Objetivo desta parte
Implementar o Quick Sort com:
- recursão;
- particionamento;
- contagem de comparações;
- contagem de movimentações.

## Complexidade
- Melhor caso: **O(n log n)**
- Caso médio: **O(n log n)**
- Pior caso: **O(n²)**

In [3]:
def quick_sort(arr):
    """Ordena uma cópia de arr usando Quick Sort.

    Retorna:
        lista_ordenada, comparacoes, movimentacoes
    """
    a = arr[:]

    comparacoes = 0
    movimentacoes = 0

    def partition(lo, hi):
        nonlocal comparacoes, movimentacoes

        pivot = a[hi]
        i = lo - 1

        for j in range(lo, hi):
            comparacoes += 1

            if a[j] <= pivot:
                i += 1
                a[i], a[j] = a[j], a[i]
                movimentacoes += 1

        a[i + 1], a[hi] = a[hi], a[i + 1]
        movimentacoes += 1

        return i + 1

    def qs(lo, hi):
        if lo < hi:
            p = partition(lo, hi)
            qs(lo, p - 1)
            qs(p + 1, hi)

    qs(0, len(a) - 1)

    return a, comparacoes, movimentacoes

### Testando o Quick Sort

In [4]:
vetor_teste = [5, 1, 4, 2, 8]

ordenado, comparacoes, movimentacoes = quick_sort(vetor_teste)

print("Vetor original :", vetor_teste)
print("Vetor ordenado :", ordenado)
print("Comparações    :", comparacoes)
print("Movimentações  :", movimentacoes)

Vetor original : [5, 1, 4, 2, 8]
Vetor ordenado : [1, 2, 4, 5, 8]
Comparações    : 8
Movimentações  : 9

---
# 3. Comparação experimental — Bubble Sort × Quick Sort

## Sobre o experimento
Os dois algoritmos são executados sobre **os mesmos vetores**, permitindo comparar a quantidade real de operações.

## Objetivo desta parte
Observar como a quantidade de operações cresce quando o tamanho da entrada aumenta.

Serão testados vetores com:
- 10 elementos;
- 20 elementos;
- 1.000 elementos.

Foi usada a semente `42` para que os mesmos dados aleatórios possam ser gerados novamente em outra execução.

In [5]:
import random

random.seed(42)

resultados = []

for n in [10, 20, 1000]:
    original = [random.randint(0, 100000) for _ in range(n)]

    _, b_cmp, b_swap = bubble_sort(original)
    _, q_cmp, q_mov = quick_sort(original)

    resultados.append({
        "n": n,
        "bubble_comparacoes": b_cmp,
        "bubble_trocas": b_swap,
        "quick_comparacoes": q_cmp,
        "quick_movimentacoes": q_mov
    })

for r in resultados:
    print(f"\nTamanho do vetor: {r['n']}")
    print(f"Bubble Sort -> comparações: {r['bubble_comparacoes']:,} | trocas: {r['bubble_trocas']:,}")
    print(f"Quick Sort  -> comparações: {r['quick_comparacoes']:,} | movimentações: {r['quick_movimentacoes']:,}")

Tamanho do vetor: 10
Bubble Sort -> comparações: 45 | trocas: 26
Quick Sort  -> comparações: 29 | movimentações: 15

Tamanho do vetor: 20
Bubble Sort -> comparações: 175 | trocas: 87
Quick Sort  -> comparações: 65 | movimentações: 41

Tamanho do vetor: 1000
Bubble Sort -> comparações: 498,324 | trocas: 243,438
Quick Sort  -> comparações: 10,218 | movimentações: 6,231

### O que os resultados mostram
O Bubble Sort apresenta crescimento **quadrático O(n²)**, enquanto o Quick Sort apresenta crescimento médio **O(n log n)**.

Por isso, conforme o tamanho do vetor aumenta, a diferença entre os dois algoritmos se torna muito mais evidente.

---
# 4. Busca sequencial em matriz

## O que este código faz
A busca sequencial percorre uma matriz posição por posição.

Como a matriz possui linhas e colunas, são utilizados **dois loops aninhados**.

## Objetivo desta parte
Localizar um valor e informar:
- se ele foi encontrado;
- linha;
- coluna;
- quantidade de comparações.

## Complexidade
No pior caso: **O(m × n)**

In [6]:
def busca_sequencial_matriz(matriz, valor):
    """Procura valor em uma matriz por varredura sequencial.

    Retorna:
        encontrado, linha, coluna, comparacoes
    """
    comparacoes = 0

    linhas = len(matriz)
    colunas = len(matriz[0])

    for i in range(linhas):
        for j in range(colunas):
            comparacoes += 1

            if matriz[i][j] == valor:
                return True, i, j, comparacoes

    return False, -1, -1, comparacoes

### Testando a busca

In [7]:
matriz = [
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
]

print("Busca por 10 :", busca_sequencial_matriz(matriz, 10))
print("Busca por 90 :", busca_sequencial_matriz(matriz, 90))
print("Busca por 999:", busca_sequencial_matriz(matriz, 999))

Busca por 10 : (True, 0, 0, 1)
Busca por 90 : (True, 2, 2, 9)
Busca por 999: (False, -1, -1, 9)

---
# 5. Experimento — Busca em matrizes de diferentes tamanhos

## Objetivo desta parte
Comparar três situações:
1. elemento na primeira posição;
2. elemento na última posição;
3. elemento inexistente.

Com isso, fica mais fácil perceber a diferença entre uma busca que termina logo no início e outra que precisa percorrer toda a matriz.

In [8]:
def criar_matriz_sequencial(linhas, colunas):
    return [
        [i * colunas + j for j in range(colunas)]
        for i in range(linhas)
    ]

In [9]:
for tamanho in [2, 10, 100]:
    matriz = criar_matriz_sequencial(tamanho, tamanho)

    primeiro = matriz[0][0]
    ultimo = matriz[-1][-1]
    inexistente = -1

    inicio = busca_sequencial_matriz(matriz, primeiro)
    fim = busca_sequencial_matriz(matriz, ultimo)
    ausente = busca_sequencial_matriz(matriz, inexistente)

    print(f"\nMatriz {tamanho} x {tamanho}")
    print("-" * 30)
    print("Total de elementos :", tamanho * tamanho)
    print("Busca no início    :", inicio[3], "comparações")
    print("Busca no fim       :", fim[3], "comparações")
    print("Valor inexistente  :", ausente[3], "comparações")

Matriz 2 x 2
------------------------------
Total de elementos : 4
Busca no início    : 1 comparações
Busca no fim       : 4 comparações
Valor inexistente  : 4 comparações

Matriz 10 x 10
------------------------------
Total de elementos : 100
Busca no início    : 1 comparações
Busca no fim       : 100 comparações
Valor inexistente  : 100 comparações

Matriz 100 x 100
------------------------------
Total de elementos : 10000
Busca no início    : 1 comparações
Busca no fim       : 10000 comparações
Valor inexistente  : 10000 comparações

---
# 6. Hands On 1 — Array de temperaturas

## O que este código faz
O exercício trabalha com um vetor contendo 10 temperaturas.

## Objetivo desta parte
Calcular:
- média;
- maior temperatura;
- menor temperatura;
- índice do maior valor;
- índice do menor valor;
- quantidade de temperaturas acima da média.

## Complexidade
Os percursos são sequenciais, portanto a complexidade permanece **O(n)**.

In [10]:
temperaturas = [
    19.0, 24.3, 21.3, 25.3, 25.6,
    16.1, 15.2, 29.2, 19.4, 19.0
]

In [11]:
# Média
soma = 0.0

for temperatura in temperaturas:
    soma += temperatura

media = soma / len(temperaturas)

# Maior e menor valor
maior = menor = temperaturas[0]
idx_maior = idx_menor = 0

for i in range(1, len(temperaturas)):
    if temperaturas[i] > maior:
        maior = temperaturas[i]
        idx_maior = i

    if temperaturas[i] < menor:
        menor = temperaturas[i]
        idx_menor = i

# Quantidade acima da média
acima_media = 0

for temperatura in temperaturas:
    if temperatura > media:
        acima_media += 1

In [12]:
print("RESULTADOS — ARRAY DE TEMPERATURAS")
print("-" * 40)
print(f"Média                : {media:.2f} °C")
print(f"Maior temperatura    : {maior:.1f} °C")
print(f"Índice do maior valor: {idx_maior}")
print(f"Menor temperatura    : {menor:.1f} °C")
print(f"Índice do menor valor: {idx_menor}")
print(f"Valores acima da média: {acima_media}")
print("Complexidade         : O(n)")

RESULTADOS — ARRAY DE TEMPERATURAS
----------------------------------------
Média                : 21.44 °C
Maior temperatura    : 29.2 °C
Índice do maior valor: 7
Menor temperatura    : 15.2 °C
Índice do menor valor: 6
Valores acima da média: 4
Complexidade         : O(n)

---
# 7. Hands On 2 — Monitoramento de sensores

## O que este código faz
Neste exemplo, a matriz representa as leituras de **5 sensores ao longo de 24 horas**.

- linha `i` → sensor;
- coluna `j` → horário;
- `sensores[i][j]` → temperatura registrada.

## Objetivo desta parte
Calcular:
- média de cada sensor;
- maior temperatura;
- sensor responsável;
- horário;
- média geral;
- quantidade de leituras acima de um limite.

## Complexidade
Os percursos completos têm complexidade **O(m × n)**.

### Dados usados na matriz
A célula abaixo contém as leituras simuladas utilizadas no relatório.

In [13]:
# Matriz simulada: 5 sensores x 24 horas
sensores = [
    [29.000000, 29.600000, 30.200000, 30.800000, 29.000000, 29.600000, 30.200000, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647, 22.597647],
    [29.600000, 30.200000, 30.800000, 29.000000, 21.864000, 30.200000, 30.800000, 29.000000, 29.600000, 21.864000, 21.864000, 21.864000, 35.000000, 21.864000, 21.864000, 21.864000, 21.864000, 21.864000, 21.864000, 21.864000, 21.864000, 21.864000, 21.864000, 21.864000],
    [30.200000, 30.800000, 29.000000, 29.600000, 30.200000, 30.800000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000, 22.380000],
    [30.800000, 29.000000, 29.600000, 30.200000, 30.800000, 29.000000, 29.600000, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471, 21.616471],
    [29.000000, 29.600000, 30.200000, 30.800000, 29.000000, 29.600000, 30.200000, 30.800000, 29.000000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000, 22.888000]
]

### Processamento das leituras

In [14]:
# 1) Média de cada sensor
medias_sensores = []

for i in range(5):
    soma = 0.0

    for j in range(24):
        soma += sensores[i][j]

    medias_sensores.append(soma / 24)

# 2) Maior temperatura, sensor e horário
maior_valor = sensores[0][0]
sensor_maior = 0
hora_maior = 0

for i in range(5):
    for j in range(24):
        if sensores[i][j] > maior_valor:
            maior_valor = sensores[i][j]
            sensor_maior = i
            hora_maior = j

# 3) Média geral
soma_total = 0.0

for i in range(5):
    for j in range(24):
        soma_total += sensores[i][j]

media_geral = soma_total / (5 * 24)

# 4) Leituras acima do limite
limite = 28.0
qtd_acima = 0

for i in range(5):
    for j in range(24):
        if sensores[i][j] > limite:
            qtd_acima += 1

print("Médias por sensor:")
for i, media_sensor in enumerate(medias_sensores):
    print(f"Sensor {i}: {media_sensor:.2f} °C")

print("\nResultados globais:")
print(f"Maior temperatura: {maior_valor:.1f} °C")
print(f"Sensor responsável: Sensor {sensor_maior}")
print(f"Horário da ocorrência: {hora_maior}h")
print(f"Média geral: {media_geral:.2f} °C")
print(f"Limite considerado: {limite:.1f} °C")
print(f"Leituras acima do limite: {qtd_acima}")
print("Complexidade dos percursos completos: O(m × n)")

Médias por sensor:
Sensor 0: 24.69 °C
Sensor 1: 25.09 °C
Sensor 2: 24.31 °C
Sensor 3: 24.02 °C
Sensor 4: 25.48 °C

Resultados globais:
Maior temperatura: 35.0 °C
Sensor responsável: Sensor 1
Horário da ocorrência: 12h
Média geral: 24.72 °C
Limite considerado: 28.0 °C
Leituras acima do limite: 38
Complexidade dos percursos completos: O(m × n)

---
# 8. Conclusão

Os códigos demonstram os principais conceitos de Estrutura de Dados II utilizados na atividade:

| Tema | Complexidade principal |
|---|---|
| Percurso em array | **O(n)** |
| Busca sequencial em matriz | **O(m × n)** |
| Bubble Sort | **O(n²)** |
| Quick Sort | **O(n log n)** em média |

Na prática, os testes mostram que dois algoritmos podem chegar ao mesmo resultado, mas gastar quantidades muito diferentes de operações para isso.

Por isso, analisar a complexidade ajuda a entender qual solução tende a funcionar melhor quando o volume de dados aumenta.

---
# 9. Nova Atividade Prática — Central de Distribuição de Pedidos

## Situação-problema
Uma central de distribuição recebe diariamente diversos pedidos que precisam ser organizados antes de serem encaminhados para separação e expedição. Cada pedido possui um código numérico de prioridade, e o sistema deve ordenar esses códigos do menor para o maior.

A equipe de desenvolvimento deseja avaliar qual algoritmo apresenta melhor comportamento conforme aumenta a quantidade de dados processados. Para isso, serão comparados quatro algoritmos de ordenação: **Bubble Sort**, **Insertion Sort**, **Selection Sort** e **Quick Sort**.

Os algoritmos de Bubble Sort e Quick Sort já foram implementados nas seções 1 e 2 deste notebook. Nesta parte, implementamos o **Insertion Sort** e o **Selection Sort** e, em seguida, executamos os quatro algoritmos lado a lado sobre os mesmos dados de entrada.

---
## Etapa 1 — Geração dos dados

Para cada tamanho de vetor (10, 20 e 1.000 elementos), será gerado **um único vetor de números aleatórios**. A partir desse vetor original, criamos quatro cópias idênticas — uma para cada algoritmo — garantindo que todos recebam exatamente os mesmos dados de entrada.

```python
vetor_bubble    = original.copy()
vetor_insertion = original.copy()
vetor_selection = original.copy()
vetor_quick     = original.copy()
```

Na prática, como cada uma das nossas funções de ordenação já recebe `arr` e internamente faz `a = arr[:]` (uma cópia própria antes de ordenar), basta passar o mesmo `original` para as quatro funções — o efeito é idêntico ao de criar as quatro cópias manualmente, e nenhuma função altera o vetor das demais.

---
## Etapa 2 — Contagem das operações

### Insertion Sort
O **Insertion Sort** constrói o vetor ordenado da esquerda para a direita, pegando um elemento de cada vez (a *chave*) e deslocando os elementos maiores que ela uma posição à frente, até achar o lugar correto.

**Critério de contagem adotado:**
- **Comparação**: cada vez que `a[j] > chave` é avaliado dentro do laço `while`.
- **Movimentação**: cada deslocamento de um elemento uma posição à frente (`a[j+1] = a[j]`). Não contamos a inserção final da chave como movimentação, pois ela ocorre uma única vez por elemento e não representa uma comparação/deslocamento de dados já ordenados.

### Selection Sort
O **Selection Sort** percorre o vetor buscando, a cada passada, o menor elemento restante e o posiciona no início da parte ainda não ordenada.

**Critério de contagem adotado:**
- **Comparação**: cada vez que `a[j] < a[idx_min]` é avaliado ao procurar o menor elemento da parte restante.
- **Troca**: uma troca (`swap`) por passada externa, e apenas quando o menor elemento encontrado não está já na posição correta (`idx_min != i`). Esse é o motivo pelo qual o Selection Sort tende a realizar bem menos trocas que o Bubble Sort ou o Insertion Sort.

### Resumo dos critérios usados nos quatro algoritmos

| Algoritmo | O que conta como **comparação** | O que conta como **troca/movimentação** |
|---|---|---|
| Bubble Sort | `a[j] > a[j+1]` | troca de elementos adjacentes (`swap`) |
| Insertion Sort | `a[j] > chave` | deslocamento de um elemento uma posição à frente |
| Selection Sort | `a[j] < a[idx_min]` | troca do elemento da posição `i` pelo menor encontrado |
| Quick Sort | `a[j] <= pivot` no particionamento | troca de elementos durante o particionamento (inclui a troca final do pivô) |

In [15]:
def insertion_sort(arr):
    """Ordena uma cópia de arr usando Insertion Sort.

    Retorna:
        lista_ordenada, comparacoes, movimentacoes
    """
    a = arr[:]
    n = len(a)

    comparacoes = 0
    movimentacoes = 0

    for i in range(1, n):
        chave = a[i]
        j = i - 1

        while j >= 0:
            comparacoes += 1

            if a[j] > chave:
                a[j + 1] = a[j]
                movimentacoes += 1
                j -= 1
            else:
                break

        a[j + 1] = chave

    return a, comparacoes, movimentacoes

In [16]:
def selection_sort(arr):
    """Ordena uma cópia de arr usando Selection Sort.

    Retorna:
        lista_ordenada, comparacoes, trocas
    """
    a = arr[:]
    n = len(a)

    comparacoes = 0
    trocas = 0

    for i in range(n - 1):
        idx_min = i

        for j in range(i + 1, n):
            comparacoes += 1

            if a[j] < a[idx_min]:
                idx_min = j

        if idx_min != i:
            a[i], a[idx_min] = a[idx_min], a[i]
            trocas += 1

    return a, comparacoes, trocas

### Testando o Insertion Sort e o Selection Sort

In [17]:
vetor_teste = [5, 1, 4, 2, 8]

ordenado, comparacoes, movimentacoes = insertion_sort(vetor_teste)
print("Insertion Sort")
print("Vetor original :", vetor_teste)
print("Vetor ordenado :", ordenado)
print("Comparações    :", comparacoes)
print("Movimentações  :", movimentacoes)

print()

ordenado, comparacoes, trocas = selection_sort(vetor_teste)
print("Selection Sort")
print("Vetor original :", vetor_teste)
print("Vetor ordenado :", ordenado)
print("Comparações    :", comparacoes)
print("Trocas         :", trocas)

Insertion Sort
Vetor original : [5, 1, 4, 2, 8]
Vetor ordenado : [1, 2, 4, 5, 8]
Comparações    : 7
Movimentações  : 4

Selection Sort
Vetor original : [5, 1, 4, 2, 8]
Vetor ordenado : [1, 2, 4, 5, 8]
Comparações    : 10
Trocas         : 2

---
## Etapa 3 — Resultados

Executamos os quatro algoritmos para os tamanhos de vetor **10, 20 e 1.000**, sempre com o mesmo vetor de origem em cada tamanho (mesma semente `42` usada na seção 3, o que também garante que os números aqui coincidem com os obtidos anteriormente para Bubble Sort e Quick Sort).

In [18]:
import random
import pandas as pd

random.seed(42)

linhas_tabela = []

for n in [10, 20, 1000]:
    original = [random.randint(0, 100000) for _ in range(n)]

    # Etapa 1 - quatro cópias idênticas do mesmo vetor
    vetor_bubble    = original.copy()
    vetor_insertion = original.copy()
    vetor_selection = original.copy()
    vetor_quick     = original.copy()

    _, b_cmp, b_swap = bubble_sort(vetor_bubble)
    _, i_cmp, i_mov  = insertion_sort(vetor_insertion)
    _, s_cmp, s_swap = selection_sort(vetor_selection)
    _, q_cmp, q_mov  = quick_sort(vetor_quick)

    linhas_tabela.append({
        "Tamanho": n,
        "Bubble Comparações": b_cmp,
        "Bubble Trocas": b_swap,
        "Insertion Comparações": i_cmp,
        "Insertion Mov.": i_mov,
        "Selection Comparações": s_cmp,
        "Selection Trocas": s_swap,
        "Quick Comparações": q_cmp,
        "Quick Mov.": q_mov,
    })

tabela_resultados = pd.DataFrame(linhas_tabela)
tabela_resultados

,Tamanho,Bubble Comparações,Bubble Trocas,Insertion Comparações,Insertion Mov.,Selection Comparações,Selection Trocas,Quick Comparações,Quick Mov.
0,10,45,26,33,26,45,6,29,15
1,20,175,87,101,87,190,15,65,41
2,1000,498324,243438,244432,243438,499500,990,10218,6231

### Tabela consolidada de resultados

| Tamanho | Bubble Comp. | Bubble Trocas | Insertion Comp. | Insertion Mov. | Selection Comp. | Selection Trocas | Quick Comp. | Quick Mov. |
|---|---|---|---|---|---|---|---|---|
| 10 | 45 | 26 | 33 | 26 | 45 | 6 | 29 | 15 |
| 20 | 175 | 87 | 101 | 87 | 190 | 15 | 65 | 41 |
| 1.000 | 498.324 | 243.438 | 244.432 | 243.438 | 499.500 | 990 | 10.218 | 6.231 |

*(A tabela acima é apenas a versão em Markdown dos valores calculados na célula anterior, incluída para facilitar a leitura do relatório.)*

---
## Etapa 4 — Análise dos resultados

**a) Qual algoritmo realizou o menor número de comparações para 10 elementos?**
O **Quick Sort** foi o mais eficiente em comparações para 10 elementos (29 comparações), seguido do Insertion Sort (33). Bubble Sort e Selection Sort empataram em 45 comparações — ambos percorrem sistematicamente todos os pares possíveis da mesma forma quando o vetor não favorece a parada antecipada.

**b) Qual algoritmo realizou menos trocas ou movimentações?**
O **Selection Sort** (apenas 6 trocas para n = 10). Isso é esperado pelo próprio critério de contagem do algoritmo: ele só troca elementos de posição uma vez por passada externa (no máximo n − 1 trocas no total), diferentemente do Bubble Sort e do Insertion Sort, que podem trocar/deslocar elementos várias vezes dentro da mesma passada.

**c) O comportamento observado para 10 elementos permaneceu semelhante quando o tamanho aumentou para 20?**
Sim, o padrão relativo entre os algoritmos se manteve: Quick Sort continuou com o menor número de comparações (65), Selection Sort continuou com o menor número de trocas (15), e Bubble/Selection continuaram sendo os que mais comparam. A diferença é que os valores absolutos cresceram de forma desproporcional entre os algoritmos — por exemplo, as comparações do Bubble Sort mais que triplicaram (de 45 para 175), enquanto as do Quick Sort pouco mais que dobraram (de 29 para 65).

**d) O que aconteceu com a quantidade de operações quando o vetor passou para 1.000 elementos?**
Houve um salto muito grande nos três algoritmos O(n²): Bubble Sort passou de 175 para 498.324 comparações, e Selection Sort de 190 para 499.500 — um crescimento de milhares de vezes para um vetor apenas 50 vezes maior. Já o Quick Sort foi de 65 para 10.218 comparações, um crescimento bem mais moderado, coerente com o comportamento O(n log n).

**e) Bubble Sort, Insertion Sort e Selection Sort apresentam complexidade O(n²) em situações típicas estudadas. Eles apresentaram exatamente a mesma quantidade de operações? Explique utilizando seus resultados.**
Não. Embora os três pertençam à mesma classe assintótica O(n²), o número exato de operações depende de como cada algoritmo compara e movimenta os dados. Para n = 1.000, Bubble Sort e Selection Sort tiveram números de comparações muito próximos (498.324 e 499.500, ambos perto de n(n−1)/2 = 499.500, pois nenhum dos dois consegue evitar boa parte das comparações mesmo com dados quase aleatórios), enquanto o Insertion Sort teve bem menos comparações (244.432) porque, na prática, ele só compara enquanto o elemento está fora de ordem e para assim que encontra a posição correta — em média, apenas metade das comparações do pior caso. Já nas trocas/movimentações, a diferença é ainda mais evidente: Selection Sort fez apenas 990 trocas contra 243.438 movimentações do Insertion Sort e 243.438 trocas do Bubble Sort. Ou seja, a complexidade O(n²) descreve a *ordem de grandeza* do crescimento, mas não garante que os algoritmos executem a mesma quantidade de operações.

**f) Qual algoritmo apresentou maior crescimento no número de operações?**
O **Selection Sort** e o **Bubble Sort** foram os que mais cresceram em número de comparações (de dezenas para praticamente 500 mil ao ir de n = 20 para n = 1.000), pois ambos sempre executam algo muito próximo de n(n−1)/2 comparações, independentemente da entrada. O Bubble Sort se destaca ainda mais quando se olha para as trocas, que também cresceram na mesma proporção quadrática.

**g) Como o comportamento experimental do Quick Sort se diferenciou dos demais algoritmos?**
O Quick Sort cresceu de forma muito mais lenta: para passar de n = 20 para n = 1.000 (50x mais elementos), suas comparações cresceram cerca de 157x (de 65 para 10.218), enquanto Bubble e Selection cresceram cerca de 2.800x e 2.600x, respectivamente. Isso ilustra na prática a diferença entre um crescimento O(n log n) e um crescimento O(n²): a curva do Quick Sort se achata muito mais conforme n aumenta.

**h) Os resultados encontrados são coerentes com as complexidades teóricas estudadas?**
Sim. Bubble Sort, Insertion Sort e Selection Sort mantiveram um número de operações da ordem de n², e o Quick Sort manteve um número de operações muito mais próximo de n log n. Isso confirma experimentalmente o que a teoria prevê: para vetores pequenos (n = 10 ou 20) a diferença entre os algoritmos é pequena e pouco relevante na prática, mas para vetores grandes (n = 1.000) a diferença se torna enorme e decisiva na escolha do algoritmo.

**i) Se você fosse responsável pelo sistema da central de distribuição e precisasse ordenar milhares de pedidos, qual dos quatro algoritmos escolheria? Justifique utilizando os resultados do experimento.**
Escolheríamos o **Quick Sort**. Nos experimentos, para 1.000 elementos ele precisou de apenas cerca de 10 mil comparações e 6 mil movimentações, contra centenas de milhares exigidas pelos outros três algoritmos. Em um sistema real de central de distribuição, o volume de pedidos tende a crescer continuamente, e a diferença de desempenho entre O(n log n) e O(n²) se torna cada vez mais crítica à medida que a quantidade de pedidos aumenta — usar Bubble, Insertion ou Selection Sort nesse cenário levaria a tempos de processamento impraticáveis conforme o volume de dados crescesse.

---
# 10. Desafio adicional (0,5) — Efeito da organização inicial dos dados

## Objetivo
Repetir o experimento utilizando três organizações diferentes de um mesmo conjunto de dados (aqui, com n = 100 elementos):
1. um vetor com números **aleatórios**;
2. o mesmo conjunto de números, mas **já ordenado**;
3. o mesmo conjunto de números, em **ordem inversa**.

A ideia é isolar o efeito da *organização inicial dos dados* sobre a quantidade de operações, mantendo os mesmos valores e o mesmo tamanho de vetor nos três casos.

In [19]:
random.seed(7)

n_desafio = 100
vetor_aleatorio = [random.randint(0, 100000) for _ in range(n_desafio)]
vetor_ordenado = sorted(vetor_aleatorio)
vetor_invertido = sorted(vetor_aleatorio, reverse=True)

cenarios = {
    "Aleatório": vetor_aleatorio,
    "Ordenado": vetor_ordenado,
    "Ordem inversa": vetor_invertido,
}

linhas_desafio = []

for nome_cenario, vetor_base in cenarios.items():
    _, b_cmp, b_swap = bubble_sort(vetor_base)
    _, i_cmp, i_mov  = insertion_sort(vetor_base)
    _, s_cmp, s_swap = selection_sort(vetor_base)
    _, q_cmp, q_mov  = quick_sort(vetor_base)

    linhas_desafio.append({
        "Cenário": nome_cenario,
        "Bubble Comparações": b_cmp,
        "Bubble Trocas": b_swap,
        "Insertion Comparações": i_cmp,
        "Insertion Mov.": i_mov,
        "Selection Comparações": s_cmp,
        "Selection Trocas": s_swap,
        "Quick Comparações": q_cmp,
        "Quick Mov.": q_mov,
    })

tabela_desafio = pd.DataFrame(linhas_desafio)
tabela_desafio

,Cenário,Bubble Comparações,Bubble Trocas,Insertion Comparações,Insertion Mov.,Selection Comparações,Selection Trocas,Quick Comparações,Quick Mov.
0,Aleatório,4944,2235,2331,2235,4950,97,651,379
1,Ordenado,99,0,99,0,4950,0,4950,5049
2,Ordem inversa,4950,4950,4950,4950,4950,50,4950,2549

### Tabela consolidada — desafio adicional (n = 100)

| Cenário | Bubble Comp. | Bubble Trocas | Insertion Comp. | Insertion Mov. | Selection Comp. | Selection Trocas | Quick Comp. | Quick Mov. |
|---|---|---|---|---|---|---|---|---|
| Aleatório | 4.944 | 2.235 | 2.331 | 2.235 | 4.950 | 97 | 651 | 379 |
| Ordenado | 99 | 0 | 99 | 0 | 4.950 | 0 | 4.950 | 5.049 |
| Ordem inversa | 4.950 | 4.950 | 4.950 | 4.950 | 4.950 | 50 | 4.950 | 2.549 |

### Análise: a organização inicial dos dados interfere na quantidade de operações da mesma maneira para todos os algoritmos?

**Não, cada algoritmo reage de forma bem diferente à organização inicial dos dados:**

- **Bubble Sort** e **Insertion Sort** são os mais sensíveis à ordem inicial. No vetor já ordenado, ambos fizeram apenas 99 comparações e **zero** trocas/movimentações — o Bubble Sort para logo na primeira passada (graças à otimização de parada antecipada) e o Insertion Sort nunca precisa deslocar elementos, pois cada novo item já está na posição correta. Já no vetor em ordem inversa, esse é o **pior caso** para os dois: cada elemento precisa ser comparado e trocado/deslocado o máximo de vezes possível (4.950 comparações e praticamente o mesmo número de trocas/movimentações).

- **Selection Sort** é o mais indiferente à organização dos dados no quesito **comparações**: ele sempre faz 4.950 comparações (n(n−1)/2) para achar o mínimo a cada passada, esteja o vetor ordenado, invertido ou aleatório — o algoritmo não tem como saber que o vetor já está ordenado sem varrê-lo. Porém, o número de **trocas** ainda varia: 0 trocas no vetor já ordenado (nunca precisa mover nada), 97 no vetor aleatório e 50 no vetor invertido.

- **Quick Sort**, com a estratégia de pivô fixo (último elemento) usada aqui, é o caso mais contraintuitivo: ele se saiu **pior** exatamente no vetor já ordenado e no invertido (4.950 comparações — seu pior caso O(n²)), e melhor no vetor aleatório (apenas 651 comparações). Isso acontece porque, com vetores já ordenados (crescente ou decrescente) e pivô sempre no último elemento, as partições ficam extremamente desbalanceadas (um lado praticamente vazio e o outro com quase todos os elementos), degenerando o algoritmo para O(n²) em vez do O(n log n) esperado no caso médio.

**Conclusão do desafio:** a organização inicial dos dados **não** afeta todos os algoritmos da mesma forma. Bubble e Insertion Sort se beneficiam bastante de dados já ordenados (melhor caso O(n)) e sofrem no pior caso (ordem inversa). Selection Sort é praticamente imune à ordem dos dados em termos de comparações, mudando apenas o número de trocas. Já o Quick Sort — que na teoria é o mais rápido em média — pode se tornar o pior de todos justamente quando os dados já estão ordenados ou totalmente invertidos, caso a escolha do pivô não seja adequada. Isso mostra, na prática, a importância de estratégias melhores de escolha de pivô (como mediana de três) quando se trabalha com dados que podem vir parcial ou totalmente ordenados, como costuma acontecer em sistemas reais de pedidos.

---
## Conclusão da atividade — Central de Distribuição de Pedidos

O experimento confirmou, com dados concretos, o que a teoria de complexidade de algoritmos prevê:

- Bubble Sort, Insertion Sort e Selection Sort pertencem à mesma classe O(n²), mas **não são equivalentes na prática** — o número real de comparações e trocas/movimentações varia bastante entre eles, e o Insertion Sort costuma ser o mais eficiente dos três em dados parcialmente ordenados.
- O Quick Sort se destacou claramente para o vetor grande (n = 1.000), exigindo muito menos operações que os demais, o que o torna a escolha natural para a central de distribuição ao lidar com milhares de pedidos.
- O desafio adicional mostrou que a **organização inicial dos dados** é tão importante quanto o algoritmo escolhido: o mesmo algoritmo pode ir do melhor para o pior caso dependendo de como os dados chegam, e isso é especialmente sensível no caso do Quick Sort com escolha de pivô ingênua (último elemento).

Na prática, para o sistema da central de distribuição, a recomendação é usar o **Quick Sort** (ou uma variação com melhor estratégia de escolha de pivô, para evitar o pior caso em dados já ordenados) como algoritmo padrão, reservando Bubble/Insertion/Selection Sort apenas para volumes muito pequenos de pedidos ou fins didáticos.